chaintope/bitcoinrb

bitcoinrb.gemspec, lib/bitcoin/network/peer_discovery.rb, lib/bitcoin/network/pool.rb, lib/bitcoin/node/configuration.rb, lib/bitcoin/node/spv.rb, lib/bitcoin/store/db/level_db.rb, spec/bitcoin/network/message_handler_spec.rb, spec/bitcoin/network/peer_discovery_spec.rb, spec/bitcoin/network/peer_spec.rb, spec/bitcoin/network/pool_spec.rb, spec/bitcoin/rpc/request_handler_spec.rb, spec/bitcoin/store/spv_chain_spec.rb
regtestで起動するとPeerDiscovery#peersで落ちる問題に対応しました。
- chain_paramsのdns_seedsが定義されていない場合は、bitcoinrb.confで定義されたノードに直接アクセスするようにしています。
- bitcoinrb.confの読み込み時に複数のconnectを指定された場合にIniFileによる読み込みでは値が上書きされて、1つのノードにしか有効にならなかったので、inifileの代わりにiniparse(https://github.com/antw/iniparse/)を使用するようにしました。
- ConfigurationのコンストラクタでBitcoin.chain_paramsを設定していましたが、Bitcoin.base_dir以前に設定をしなければ対応するbitcoinrb.confを読み込まないようになっていたので、修正しました。
=> Fix peer discovery process when no dns seeds

lib/openassets/payload.rb, spec/openassets/payload_spec.rb
metadataに0x01, 0x02,...などのバイナリーを設定した時にto_payloadで0パディングされない問題に対応しました。
参照: https://github.com/haw-itn/openassets-ruby/pull/19
=> Payload#to_payload supports binary metadata.

lib/bitcoin/network/message_handler.rb
BitcoinCoreのフルノードは、VerAck受信前にsendheadersなどのメッセージを受信した場合、エラーとして処理している。
bitcoinrbではノードへVerAckを送信する前にハンドシェイク完了する処理を行い、続けてsendheadersメッセージを送信していた。このため、タイミングによってはノード側でエラーとなっていた。
VerAckメッセージを送受信が完了した時点でハンドシェイクの処理を続行するように修正しました。
=> Handshake must be established only after verack message is sent and received

lib/bitcoin/wallet/account.rb
- A `derive_path` is not defined in Account class.
```
$ ./bin/console 
irb(main):001:0> wallet = Bitcoin::Wallet::Base.create(1, "./")
irb(main):002:0> account = wallet.accounts.first
irb(main):003:0> account.derive_receive(0)
NoMethodError (undefined method `derive_path' for #<Bitcoin::Wallet::Account:0x00007fe3268cb5e8>
Did you mean?  derive_change)
```
- #derived_change_keys returns array whose size is `receive_depth` . its size should be `change_depth` ??
=> Account#derive_receive(index) fails in NoMethodError.

lib/bitcoin/network/connection.rb, lib/bitcoin/network/message_handler.rb
When I tried to broadcast an invalid transaction through RPC request, SPV node received a get_data message from the remote peer.
I think that a receiving node(SPV node):
(1) SHOULD NOT close the connections to other peers.
(2) SHOULD ignore any get_data messages (or respond correct data to the peer).
```
I, [2018-06-11T16:09:24.078488 #26357 #70270959459780]  INFO -- : process http request. command = sendrawtransaction
I, [2018-06-11T16:09:24.084998 #26357 #70270959459780]  INFO -- : send message tx
I, [2018-06-11T16:09:24.085229 #26357 #70270959459780]  INFO -- : send message tx
I, [2018-06-11T16:09:24.085364 #26357 #70270959459780]  INFO -- : send message tx
I, [2018-06-11T16:09:24.085497 #26357 #70270959459780]  INFO -- : send message tx
I, [2018-06-11T16:09:24.245564 #26357 …
```
=> Fix connection closing when receiving getdata

lib/openassets.rb, lib/openassets/util.rb, spec/openassets/util_spec.rb
This PR is ported from openassets-ruby.
=> Implement OpenAssets::Util.script_to_asset_id

lib/bitcoin/merkle_tree.rb, lib/bitcoin/network/message_handler.rb, lib/bitcoin/network/peer.rb, spec/bitcoin/merkle_tree_spec.rb, spec/bitcoin/network/peer_spec.rb
This PR implements 
1.  notification to observers when the spv node is received `merkleblock` message from the peer.
2. methods for calculating the transaction index within the block.
Calculating the index is required for Lightning Network 
(see `short_channel_id` description in https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#requirements)
=> Merkleblock

lib/bitcoin/rpc/request_handler.rb, lib/bitcoin/wallet/base.rb, spec/bitcoin/wallet/wallet_spec.rb
This PR solve #31.
I run below, it is complete.
```
$ ./bin/console 
irb(main):001:0> wallet = Bitcoin::Wallet::Base.create(99999)
=> #<Bitcoin::Wallet::Base:0x00007fc72d101ef8 @path="/Users/okumura/.bitcoinrb/mainnet/db/wallet/wallet99999/", @db=#<Bitcoin::Wallet::DB:0x00007fc72c9f1dc0 @level_db=<LevelDB::DB "/Users/okumura/.bitcoinrb/mainnet/db/wallet/wallet99999/">, @master_key=#<Bitcoin::Wallet::MasterKey:0x00007fc72d0b4860 @mnemonic=["piece", "return", "maid", "learn", "dish", "stereo", "snow", "melt", "bounce", "lottery", "shock", "empty", "miss", "govern", "carpet", "tail", "turn", "often", "junior", "monster", "tell", "warrior", "grab", "candy"], @seed="67c0098389f99da10a5d15f7b65b9f095d60f77c6a1bff4a0b7185c6f09482872dab3ee80235791cccc5eab540a12b2e52bec0ba81b551c35a30d3114f7fe983", …
```
=> Fix creating a wallet after changing Bitcoin.chain_params fails. (#31)

lib/bitcoin/key.rb, lib/bitcoin/secp256k1/native.rb, lib/bitcoin/secp256k1/ruby.rb, spec/bitcoin/secp256k1/native_spec.rb, spec/bitcoin/secp256k1/ruby_spec.rb, spec/bitcoin/wallet/wallet_spec.rb
This PR makes Bitcoin::Key generation faster in case of using libsecp256k1 library.
Up to now, `Bitcoin::Key#generate_pubkey` has been based on pure Ruby implementation from 'ecdsa' gem. This PR change the method so that it may use native implementation in libsecp256k1( if libsecp256k1 library has been installed).
before:
```
irb(main):001:0> require "benchmark"
=> true
irb(main):002:0> puts Benchmark.measure { Bitcoin::Key.new(priv_key: "206f3acb5b7ac66dacf87910bb0b04bed78284b9b50c0d061705a44447a947ff") }
[Warning] Use key_type parameter instead of compressed. compressed parameter removed in the future.
0.100302   0.001502   0.101804 (  0.104396)
=> nil
```
after:
```
irb(main):001:0> require "benchmark"
=> true
irb(main):002:0> puts Benchmark.measure { Bitcoin::Key.new(priv_key: …
```
=> Performance in bitcoin key generation

lib/bitcoin/store/spv_chain.rb, spec/bitcoin/store/spv_chain_spec.rb
SPVChain#find_entry_by_hash raises the following RuntimeError when a hash is not stored in the database. (It occurs on blockchain reorganization.)
```
TypeError:
no implicit conversion of nil into String
```
on the other hand, SPVChain#append_header(header) seems to design that  SPVChain#find_entry_by_hash returns nil (or false) and #append_header raise error "header's previous hash..."
```
unless find_entry_by_hash(header.block_hash)
raise "header's previous hash(#{header.prev_hash}) does not match current best block's(#{best_block.block_hash})."
end
```
=> SPVChain#find_entry_by_hash raises UNEXPECTED error

lib/bitcoin/util.rb, lib/openassets/payload.rb, spec/bitcoin/util_spec.rb, spec/openassets/marker_output_spec.rb
Bitcoin users can set arbitrary OP_RETURN data to their own transactions.
So I think that OpenAssets::MarkerOutput#open_assets_marker method should return true/false value for any op_return data, but runtime error occurs for some payload such as '4f410100018f8f'.
```
irb(main):004:0>  script = Bitcoin::Script.new << Bitcoin::Opcodes::OP_RETURN << '4f410100018f8f'
=> #<Bitcoin::Script:0x00007fdf07ab1c68 @chunks=["j", "\aOA\x01\x00\x01\x8F\x8F"]>
irb(main):005:0> Bitcoin::TxOut.new(script_pubkey: script).open_assets_marker?
Traceback (most recent call last):
10: from ./bin/console:14:in `<main>'
9: from (irb):5
8: from /Users/h_yamaguchi/Documents/Projects/chaintope/raijin_project/bitcoinrb/lib/openassets/marker_output.rb:8:in `open_assets_marker?'
7: from …
```
=> OpenAssets::MarkerOutput#open_assets_marker? should not raise error

lib/bitcoin/ext_key.rb, lib/bitcoin/key.rb, spec/bitcoin/bip143_spec.rb, spec/bitcoin/ext_key_spec.rb
A key type for P2SH-P2WPKH (SegWit public key inside P2SH) defined in bip-0178 is "P2WPKH_P2SH"
=> Fix typo in Bitcoin::Key::TYPES

lib/bitcoin/store/spv_chain.rb, spec/bitcoin/store/spv_chain_spec.rb
getblockchaininfo in regtest mode fails when block height < 11 ( = Bitcoin::MEDIAN_TIME_SPAN ).
```
curl -X POST "http://localhost:18443" --data '{"jsonrpc": "2.0", "method": "getblockchaininfo", "params": []}'
undefined method `header' for nil:NilClass
```
This RP solves this problem.
=> Fix for error on calling rpc getblockchaininfo in regtest mode

bitcoinrb.gemspec, lib/bitcoin/rpc/bitcoin_core_client.rb, spec/bitcoin/rpc/bitcoin_core_client_spec.rb, spec/spec_helper.rb
`Bitcoin::RPC::BitcoinCoreClient` raise `TypeError` when server respond with error messages, but expected to `RuntimeError`.
This pull-request is fix this.
```ruby
@client = Bitcoin::RPC::BitcoinCoreClient.new(config)
@client.getblock("INVALID_BLOCK_HASH")
> TypeError (exception class/object expected)
@client.getblock("INVALID_BLOCK_HASH")
> RuntimeError ({"code"=>-8, "message"=>"blockhash must be of length 64 (not 18, for 'INVALID_BLOCK_HASH')"})
```
Add  [WebMock](https://github.com/bblimke/webmock) gem for stubbing http-request in test.
=> Fix `Bitcoin::RPC::BitcoinCoreClient` raises unexpected error.

lib/bitcoin/rpc/bitcoin_core_client.rb, spec/bitcoin/rpc/bitcoin_core_client_spec.rb
This pull-request is allow to call Bitcoin Core cli command on Ruby-like method names.
```ruby
@client = Bitcoin::RPC::BitcoinCoreClient.new(config)
@client.getblockcount
> 1
@client.get_block_count
> 1
```
=> Call CLI command on Ruby-like method names.

lib/bitcoin.rb, lib/bitcoin/payment_code.rb, spec/bitcoin/payment_code_spec.rb
Implement v1 of [BIP47](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki#Abstract) Payment Code to bitcoinrb.  
This PR achieved following features.
- Generate Payment Code
- Decode Payment Code
- Generate notification address
- Notification transaction
- Sending transaction
- Whole v2 implementation
=> Implement BIP47 Payment Code and notification address

lib/bitcoin/rpc/bitcoin_core_client.rb, spec/bitcoin/rpc/bitcoin_core_client_spec.rb
BitcoinCoreClient is expected to send requests with `/wallet/[wallet_name]` path, when `config[:wallet]` is set.
However the current impl is not work as that.
This PR is going to fix it.
=> Fix multi wallet support.

lib/bitcoin.rb, spec/bitcoin_spec.rb
Changed to use ord because each_byte method was slow.
Benchmark results are listed below.
```
raw_tx = "01000000000101cdf9ce825aba7f777899cc76243946a62d9ecb6c9805d30faa5a690d862344d70000000000ffffffff0253a2800200000000160014e3324f11cd2d4715c9d09186d0677d3f18fc0cc8e8c61100000000001976a91498cba7ee7618b76d19b4952a4240b954609b75cb88ac0247304402204ed43722821e458b98295824079ad4a04f5a55df8aa3339e89ebc7138d45e1ca022076b925a51996eb2797a0f870855d73220950e7a91d5d8f0cc11bc9e2c68551ba012103e67c2c0435bd1b6478ae327e4746d788a01e2f6e669506cb1a0515b9a708c74b00000000"
```
【before】
```ruby
irb > n = 100000
irb > Benchmark.bm do |x|
irb >   x.report { n.times do ; Bitcoin::Tx.parse_from_payload(raw_tx.htb); end }
irb > end
user     system      total        real
5.003670   0.378110   5.381780 (  5.390959)
=> …
```
=> Fix opcode method to use ord

lib/bitcoin/script/script.rb, spec/bitcoin/script/script_spec.rb
Bitcoin::Script#type returns `nonstandard` for p2tr output scripts.
This patch changes this behaviour to return `WITNESS_V1_TAPROOT` for the `type` method instead.
=> Add WITNESS_V1_TAPROOT type to P2TR output scripts

lib/bitcoin/script/script.rb
When going through the code stumbled upon this one. Was a bit confusing. No noticeable effect on the time of running the specs (8 minutes and 25 seconds)
=> Remove idle buf.eof check
